#
# Service Discovery
#
consul:
  # replace advertise IP with main interface ROUTABLE_IP
  command: -server -bootstrap -advertise 10.0.2.15
  image: progrium/consul:latest
  ports:
   - "8300:8300"
   - "8400:8400"
   - "8500:8500"
   - "8600:53/udp"
#
# Service Registry Bridge
#
registrator:
  command: -ip=10.0.2.15 consul://consul:8500
  image: gliderlabs/registrator:v5
  links:
   - consul
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
#
# Reverse Proxy / Load Balancer
#
haproxy:
  build: haproxy/
  links:
   - consul
  ports:
   - "80:80"
   - "70:70"
  environment:
   - SERVICE_PLATFORM=dev
   - SERVICE_TAGS=frontend
   - SERVICE_80_NAME=haproxy-80
   - SERVICE_70_NAME=haproxy-70
#
# Static Web Server (SPA)
#
static:
  extends:
    file: ../spa-client/docker-compose-common.yml
    service: static
  ports:
    - "3000"
  environment:
    - SERVICE_PLATFORM=dev
    - SERVICE_3000_NAME=static
    - SERVICE_5800_NAME=static-debug
    - SERVICE_TAGS=frontend
    - STATIC_WEBROOT=./dist
    - STATIC_STUBS=0
    - STATIC_API_BASE_URL=http://localdocker/api
  links:
    - consul
#
# Web API Server
#
webapi:
  extends:
    file: ../spa-api-server/docker-compose-common.yml
    service: webapi
  ports:
    - "8100"
  environment:
    - SERVICE_PLATFORM=dev
    - SERVICE_TAGS=frontend
    - SERVICE_8100_NAME=webapi
    - SERVICE_5810_NAME=webapi-debug
    - API_RDB_CONN=db:28015
    - API_BASE_URL=/api
  links:
    - consul
    - db
#
# Backend Database
#
db:
  extends:
    file: ../spa-api-server/docker-compose-common.yml
    service: db
  ports:
    - "8080:8080"
    - "28015:28015"
